# --------------------------------
# kod_05_left.conf
# 左側 = peripheral + encoder
# --------------------------------

CONFIG_LOG=n

# 左には PS/2 実体がないので不要
# CONFIG_ZMK_POINTING is not needed here
# CONFIG_INPUT is not needed here
CONFIG_ZMK_POINTING=y
# 左はエンコーダだけなら追加設定ほぼ不要
