# --------------------------------
# kod_05_right.conf
# 右側 = central + PS/2 TrackPoint
# --------------------------------

CONFIG_ZMK_SPLIT_ROLE_CENTRAL=y

CONFIG_LOG=n

CONFIG_ZMK_POINTING=y
CONFIG_INPUT=y

CONFIG_ZMK_INPUT_MOUSE_PS2_ENABLE_ERROR_MITIGATION=n

CONFIG_SERIAL=y
CONFIG_UART_ASYNC_API=y
CONFIG_UART_USE_RUNTIME_CONFIGURE=y
CONFIG_ZMK_BLE_EXPERIMENTAL_CONN=y

CONFIG_ZMK_STATUS_ADVERTISEMENT=y
CONFIG_ZMK_STATUS_ADV_KEYBOARD_NAME="kod05"
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_FETCHING=y
CONFIG_ZMK_STATUS_ADV_CENTRAL_SIDE="RIGHT"
